version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - apicurio
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: [ "npm", "start" ]

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: apicurio
      POSTGRES_PASSWORD: apicurio
      POSTGRES_DB: apicurio
    volumes:
      - apicurio_pgdata:/var/lib/postgresql/data

  apicurio:
    image: quay.io/apicurio/apicurio-registry-sql:2.5.10.Final
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      REGISTRY_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apicurio
      REGISTRY_DATASOURCE_USERNAME: apicurio
      REGISTRY_DATASOURCE_PASSWORD: apicurio
      REGISTRY_SQL_INIT: true  # Initialize schema on first run
    volumes:
      - apicurio_data:/var/lib/apicurio

volumes:
  apicurio_pgdata:
  apicurio_data:
