version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - apicurio
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: [ "npm", "start" ]

  apicurio:
    image: quay.io/apicurio/apicurio-registry-mem:2.5.10.Final
    ports:
      - "8081:8080"

